---
- name: update homebrew
  community.general.homebrew:
    update_homebrew: true
  when: ansible_facts['os_family'] == 'Darwin'

- name: Add Homebrew taps
  community.general.homebrew_tap:
    name:
      - heroku/brew
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
